apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-redis-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sivateja-M/springboot.git'  
    path: k8s 
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated: {}  
    syncOptions:
      - CreateNamespace=true

